### PR TITLE
Fix remove structures

### LINKED ISSUE #171: Field deletion doesn't work well in SSA
k8s version is 1.19.1.

I first created the following by using `kubectl apply --server-side -f backendconfig.yaml`
```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: bar
  namespace: default
spec:
  connectionDraining:
    drainingTimeoutSec: 30
  securityPolicy:
    name: bol-default-policy
```

The following is what has been created and persisted:
```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  creationTimestamp: "2020-09-11T18:18:40Z"
  generation: 1
  managedFields:
  - apiVersion: cloud.google.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:connectionDraining:
          f:drainingTimeoutSec: {}
        f:securityPolicy:
          f:name: {}
    manager: kubectl
    operation: Apply
    time: "2020-09-11T18:18:40Z"
  name: bar
  namespace: default
  resourceVersion: "214762"
  selfLink: /apis/cloud.google.com/v1/namespaces/default/backendconfigs/bar
  uid: 8d90b477-994f-4091-b631-95f19ad10730
spec:
  connectionDraining:
    drainingTimeoutSec: 30
  securityPolicy:
    name: bol-default-policy
```

Then I tried to re-apply the following using `kubectl apply --server-side -f backendconfig.yaml`
```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: bar
  namespace: default
spec:
  # <=========== connectionDraining field is removed.
  securityPolicy:
    name: bol-default-policy
```
I got error:
```
The BackendConfig "bar" is invalid: spec.connectionDraining: Invalid value: "null": spec.connectionDraining in body must be of type object: "null"
```
I also tried to re-apply the following using `kubectl apply --server-side -f backendconfig.yaml`
```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: bar
  namespace: default
spec:
  connectionDraining: null  # <======= connectionDraining is set to null
  securityPolicy:
    name: bol-default-policy
```
I got the same error:
```
The BackendConfig "bar" is invalid: spec.connectionDraining: Invalid value: "null": spec.connectionDraining in body must be of type object: "null"
```

On the other hand, I tried to update the created object with `kubectl replace -f backendconfig.yaml`
```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: bar
  namespace: default
spec:
  connectionDraining: null  # <======= connectionDraining is set to null
  securityPolicy:
    name: bol-default-policy
```
I got the same schema validation error as SSA above.

But if I run `kubectl replace` with the following, it can successfully remove the field w/o error.
```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: bar
  namespace: default
spec:
  # <========== connectionDraining field is removed.
  securityPolicy:
    name: bol-default-policy
```

I have played with SMD v4 libary a bit, my understanding is that:
SMD v4 set the field as `null` in the merged object when it infers the user want to delete the field.
In this case, initially it is
```
spec:
  connectionDraining:
    drainingTimeoutSec: 30
  securityPolicy:
    name: bol-default-policy
```
Then I SSA:
```
spec:
  securityPolicy:
    name: bol-default-policy
```
In the apiserver, SMD v4 merged the object as the following before the object goes to the validation:
```
spec:
  connectionDraining: null
  securityPolicy:
    name: bol-default-policy
```

The OpenAPI schema validation rejects the object since the `connectionDraining` field is an object:
```
              connectionDraining:
                description: ConnectionDrainingConfig contains configuration for connection
                  draining. For now the draining timeout. May manage more settings
                  in the future.
                properties:
                  drainingTimeoutSec:
                    description: Draining timeout in seconds.
                    format: int64
                    type: integer
                type: object
```

### PR DESCRIPTION
**Pull request by apelisse**
Fixes #171 

This fixes a bug and slightly changes an existing behavior.

Struct that have a null value will now be owned, i.e.
```
struct:
```
will now be owned by whoever applies that (currently, these can't be owned, which means we may accidentally drop the empty struct).

Also, removing a struct will now remove all the items that are not owned by someone else in it (including things that are owned by an updater).

### CODE REVIEW

**Comment by jpbetz** [comment]
I just did a pass on the [WG API Expression: Unsetting fields](https://docs.google.com/document/d/11gUQY7Qvs1m53RTWzDzbOcDUZYMNRQCBQbTukpxmpSg/edit#heading=h.qm34ds8b1z19) to make sure we're not contradicting anything we decided on there. I think we're OK there.

**Comment by jpbetz** [comment]
> Struct that have a null value will now be owned, i.e.
> 
> ```
> struct:
> ```

By "null" we really just mean "empty struct" here, right? In [WG API Expression: Unsetting fields](https://docs.google.com/document/d/11gUQY7Qvs1m53RTWzDzbOcDUZYMNRQCBQbTukpxmpSg/edit#heading=h.qm34ds8b1z19) I remember that we were deliberately trying to avoid the distinction between `struct: null` and `struct:`.

**Comment by jpbetz** [comment]
> Also, removing a struct will now remove all the items that are not owned by someone else in it (including things that are owned by an updater).

Can we say more about the motivation for this in the PR description? This seems to complicate how the [ownership transfer](https://kubernetes.io/docs/reference/using-api/server-side-apply/#transferring-ownership) mechanism of Server Side Apply behaves-- updater ownership is now handled differently. Or were we already handling it differently and I just wasn't aware?

File: fieldpath/set.go [hunk 1]
```diff
@@ -110,6 +110,23 @@ func (s *Set) RecursiveDifference(s2 *Set) *Set {
 	}
 }
 
+// NestedSet returns a Set that contains all the fields in s, as well as
```
Comment (lavalamp) [inline fieldpath/set.go:113]: `NestedSet` is not a good name, I think the name should include something about ensuring all children are also members. `RecursivelyCompletelyCoveredSet` or something like that? `EnsureAllChildrenAreMembers`?

Comment (lavalamp) [reply fieldpath/set.go:113]: `EnsureNodesAreMembers`

File: merge/ignore_test.go [hunk 2]
```diff
@@ -174,10 +174,8 @@ func TestIgnoredFieldsUsesVersions(t *testing.T) {
 					APIVersion: "v2",
 				},
 				Apply{
-					Manager: "apply-one",
-					Object: `
-						mapOfMapsRecursive:
-					`,
+					Manager:    "apply-one",
+					Object:     ``,
```
Comment (lavalamp) [inline merge/ignore_test.go:178]: hm I can see why you changed this test case but I think we need to know what the output is if clients change nothing?

File: typed/tofieldset.go [hunk 3]
```diff
@@ -137,7 +137,9 @@ func (v *toFieldSetWalker) visitMapItems(t *schema.Map, m value.Map) (errs Valid
 		v2 := v.prepareDescent(pe, tr)
 		v2.value = val
 		errs = append(errs, v2.toFieldSet()...)
-		if _, ok := t.FindField(key); !ok {
+		if val.IsNull() || (val.IsMap() && val.AsMap().Length() == 0) {
```
Comment (lavalamp) [inline typed/tofieldset.go:140]: zero length maps but not zero length lists? That's surprising?

File: merge/nested_test.go [hunk 4]
```diff
@@ -500,6 +512,124 @@ func TestUpdateNestedType(t *testing.T) {
...
+					APIVersion: "v1",
+				},
+				Apply{
+					Manager: "default",
+					Object: `
+					`,
+					APIVersion: "v1",
+				},
+			},
+			Object: `
```
Comment (lavalamp) [inline merge/nested_test.go:596]: This result is wrong, `default` should no longer have owned any fields after the controller stomped them, so they should not be removed.

Comment (apelisse) [reply merge/nested_test.go:596]: The controller owns only the things that it changed, we can't know it wants to own name or not.

Comment (apelisse) [reply merge/nested_test.go:596]: But this is still wrong, because controller should still own value and that should be preserved. Yes, that's what I'm trying to change right now.

File: merge/nested_test.go [hunk 5]
```diff
@@ -500,6 +512,124 @@ func TestUpdateNestedType(t *testing.T) {
...
+					Manager: "default",
+					Object: `
+						struct: {}
+					`,
+					APIVersion: "v1",
+				},
+			},
+			Object: `
+				struct:
+				  value: 1
```
Comment (lavalamp) [inline merge/nested_test.go:629]: This is also wrong, the user stopped expressing an opinion about `struct.name`. However, they co-owned that along with the controller. Since the controller still expresses an opinion, the field should remain.

File: merge/ignore_test.go (hunk 2 above)
Comment (lavalamp) [reply merge/ignore_test.go:178]: I guess my ask is, leave all the inputs the same and change the outputs in these tests. And copy the cases and modify them if you want to test different inputs.

File: merge/nested_test.go (hunk 4 above)
Comment (lavalamp) [reply merge/nested_test.go:596]: oh that's a good point, it was an update. Yeah, the result here is that `struct.value` should exist and = 1.

File: merge/nested_test.go (hunk 5 above)
Comment (lavalamp) [reply merge/nested_test.go:629]: I take it back, the update shouldn't take ownership of the name field. so this seems right.

Comment (apelisse) [reply merge/nested_test.go:629]: I'll still add a test where update took over the name too and see what happens.

File: typed/tofieldset.go (hunk 3 above)
Comment (apelisse) [reply typed/tofieldset.go:140]: Actually, this is specific to struct fields with no values, it's not relevant for lists.

File: merge/ignore_test.go (hunk 2 above)
Comment (apelisse) [reply merge/ignore_test.go:178]: I've made the change you requested. I understand that as a reviewer you want to see how the behavior changed, but I think the test is better the way it was written before.

File: merge/multiple_appliers_test.go [hunk 6]
```diff
@@ -554,11 +554,10 @@ func testMultipleAppliersFieldUnsetting(t *testing.T, v1, v2, v3 fieldpath.APIVe
 					`,
 				},
 			},
-			Object: typed.YAMLObject(fmt.Sprintf(`
+			Object: typed.YAMLObject(`
 				struct:
 				  name: a
-				  complexField_%s: null
```
Comment (lavalamp) [inline merge/multiple_appliers_test.go:560]: is this case still tested?

Comment (apelisse) [reply merge/multiple_appliers_test.go:560]: Joe had to write the test with the "dangling" struct only because of this bug that I'm fixing. This is the bug fix :-)
